# Problemas Laboratório 6 {-}

Estes problemas são relacionados ao assunto abordado no Laboratório \@ref(lab6).

## Problema 6.1 {-}

Considere a equação diferencial \@ref(eq:eq61), com $\beta = 0.01$, $A = 1$. Implemente o diagrama de blocos da Figura \@ref(fig:fig62) no Simulink/Matlab com o objetivo de simular a dinâmica da altura do nível $H$ do tanque. Simule o sistema para a condição $H(0) = 0$ e vazões de entrada $Q_e = 0.01$, $Q_e = 0.02$, $Q_e = 0.1$ do tipo degrau. Analise os resultados. Observe a não-linearidade do sistema: ao dobrarmos a vazão de entrada de $Q_e = 0.01$ para $Q_e = 0.02$ o valor final de $H(t)$ quadruplicou.

#### Resolução {-}

Working on it :)

## Problema 6.2 {-}

Utilizando os mesmos dados do item anterior simule o sistema para a condição inicial $H(0)=4$ e a vazão de entrada $Q_e = 0.02$ do tipo degrau. O comportamento observado era esperado? Justifique (dica: veja \@ref(eq:eq63) e relembre o conceito de ponto de equilíbrio). Em seguida, modifique a vazão de entrada para $Q_e = 0.019$ e simule. Analise os resultados (veja a Propriedade 1 e \@ref(eq:eq63)).

#### Resolução {-}

Working on it :)

## Problema 6.3 {-}

Considere $G(s)$ em \@ref(eq:eq69), que é a Função de Transferência do sistema linearizado associado ao sistema de um tanque \@ref(eq:eq66) no ponto de equilíbrio $(\overline{H}, \overline{u}) = (4, 0.02)$. Implemete no Simulink/Matlab o diagrama de blocos apresentado na Figura \@ref(fig:fig63) com o objetivo de comparar a dinâmica de $\overline{H} + \delta H(t)$ com a dinâmica de $H(t)$ do sistema não-linear \@ref(eq:eq66). Para isto, escolha $\overline{u} = 0.02, \delta u = 0$, e determine $t_1 > 0$ por simulação (veja \@ref(eq:eq610)). Simule para $\delta u = 0.0001, \delta u = 0.001, \delta u = 0.01$ do tipo degrau e analise os resultados. Baseado no que vimos em aulas anteriores, quais são as características dinâmicas de saída $\delta y(t) = \delta H(t)$ do sistema linearizado (por exemplo: sobressinal, tempo de acomodação, valor em regime permanente)? Tais características eram esperadas? Justifique sua resposta (dica: veja \@ref(eq:eq69)).

#### Resolução {-}

Working on it :)

## Problema 6.4 {-}

No item anterior, mude o ponto de equilíbrio do sistema de um tanque para $(\overline{H}, \overline{u}) = (16, 0.04)$, mas mantenha a mesma Função de Transferência $G(s)$ de antes. Simule e analise os resultados. Tal comportamento era esperado? Justifique sua resposta.

#### Resolução {-}

Working on it :)