# Problemas Laboratório 8 {-}

Estes problemas são relacionados ao assunto abordado no Laboratório \@ref(lab8).

Utilize o comando `rlocus` e o pacote `rltool` do Matlab para determinar o LGR de cada $G(s)$ abaixo.

## Problema 8.1 {-}

Considere o sistema de primeira ordem
$$
G(s) = \frac{0.5}{10s + 1}
$$

a. Determine  o LGR e observe que o sistema em malha-fechada é estável para qualquer $K>0$.
b. Encontre $K$ de modo que o pólo em malha-fechada seja $s = -0.2$ e simule para $r(t)$ do tipo degrau unitário. Determine $t_s(5\%)$ e visualize o sinal de controle.
c. Repita o item anterior para $s = -0.4$ e compare. Note que $t_s(5\%)$ diminui pela metade e que a amplitude do sinal de controle aumentou. Justifique tal comportamento (dica: veja \@ref(eq:eq81)).

#### Resolução {-}

Working on it :)

## Problema 8.2 {-}

Considere o sistema de primeira ordem
$$
G(s) = \frac{0.5}{s-1} \text{ (instável)}
$$

a. Determine o LGR. Encontre a faixa de valores de $K$ no sistema em malha-fechada é instável e a faixa de valores em que é estável.
b. Escolha $K=1$ (instável) e $K=3$ (estável) e simule para $r(t)$ do tipo degrau unitário.

#### Resolução {-}

working on it :)

## Problema 8.3 {-}

Considere o sistema de segunda ordem
$$
G(s) = \frac{0.9}{s(s+1)} = \frac{0.9}{s^2+s}
$$

a. Determine o LGR e observe que o sistema em malha-fechada é estável para qualquer $K>0$.
b. Determine a faixa e valores de $K$ em que os pólos são reais. Simule para $K=0.2$ com $r(t)$ do tipo degrau unitário. Observe que, conforme o esperado, não há sobressinal. Justifique.
c. Determine a faixa de valores $K$ em que os pólos são complexos conjugados. Simule para $K = 0.55$ e $K = 1.3$ com $r(t)$ do tipo degrau unitário. Analise os resultados. Note que, conforme o esperado, o sobressinal aumentou. Justifique.

#### Resolução {-}

Working on it :)

## Problema 8.4 {-}

Considere o sistema de segunda ordem
$$
G(s) = \frac{1.2}{(s+1)(s+3)} = \frac{1.2}{s^2+4s+3}
$$

a. Determine o LGR e observe que o sistema em malha-fechada é estável para qualquer $K>0$.
b. Adicione um pólo em $s=0$ (integrador). Note que o LGR foi "empurrado" para a direita. Determine a faixa de valores de $K$ em que o sistema em malha-fechada é estável e a faixa em que é instável. Simule para $K = 2.5$ com $r(t)$ do tipo degrau unitário e perceba que $e(\infty) = 0$. Isto era esperado? Justifique (dica: determine os pólos de malha-fechada e note que eles estão no SPE).
c. Mantenha o pólo em $s=0$ e adicione um zero em $s=-2$. Note que o LGR foi "atraído" em sua direção e que temos estabilidade para qualquer $K>0$. Por fim, mude a posição do zero para $s=2$ (sistema de fase não-mínima). Determine a faixa de valores de $K$ em que o sistema em malha-fechada é estável e a faixa de valores em que é instável. Isto mostra que sistemas de fase não-mínima exigem bastante cuidado em termos de estabilidade. Simule para $K=6$ com $r(t)$ do tipo degrau unitário. Como $G(s)$ tem um pólo em $s=0$, não deveríamos ter que $e(\infty) = 0$? Justifique.

#### Resolução {-}

Working on it :)

## Problema 8.5 {-}

Considere o sistema de segunda ordem
$$
G(s) = \frac{0.8}{s(s+3)} = \frac{0.8}{s^2 + 3s}
$$

a. Determine a região do LGR em que o sistema em malha-fechada apresenta $M_p \leq 5\% (\implies \xi \geq 0.7)$.
b. Escolha $K$ de modo que $M_p = 5\% (\xi = 0.7)$. Determine os pólos de malha-fechada e simule para $r(t)$ do tipo degrau unitário. Verifique se o sobressinal resultante está de acordo com $K$. Note que $e(\infty)=0$. Isto era esperado? Justifique.

#### Resolução {-}

Working on it :)



## Problema 8.6 {-}

Analise o LGR de
$$
G(s) = \frac{s+1}{s^2(s+4)} = \frac{s+1}{s^3+4s^2}
$$

#### Resolução {-}

Working on it :)
